
import React from 'react';

const InfoIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-sky-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
);

const Feature: React.FC<{ title: string; description: string }> = ({ title, description }) => (
  <div>
    <h3 className="text-lg font-semibold text-slate-800 dark:text-white">{title}</h3>
    <p className="mt-1 text-slate-600 dark:text-slate-400">{description}</p>
  </div>
);

export const InfoCard: React.FC = () => {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-lg p-6 md:p-8 animate-fade-in">
      <div className="flex items-start space-x-4">
        <div className="flex-shrink-0">
          <InfoIcon />
        </div>
        <div>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">Welcome to the Hydro Data Fetcher</h2>
          <p className="mt-1 text-slate-600 dark:text-slate-400">
            This tool simulates fetching rainfall data based on the features of the PC-HYDRO 7.4 tool. 
            Enter coordinates above and click "Fetch Rainfall Data" to begin.
          </p>
        </div>
      </div>
      <div className="mt-6 border-t border-slate-200 dark:border-slate-700 pt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
        <Feature 
          title="Objective" 
          description="To provide a user-friendly interface for retrieving simulated hydrologic data for any location, mimicking professional engineering tools." 
        />
        <Feature 
          title="Required Input" 
          description="Enter the Latitude and Longitude for your location of interest. Pima County, AZ coordinates are pre-filled as an example." 
        />
        <Feature 
          title="Expected Results" 
          description="A detailed table of precipitation frequency estimates (rainfall intensity in in/hr) for various storm durations and return periods." 
        />
        <Feature 
          title="Data Export" 
          description="Once the data is displayed, you can download the entire table as a .CSV file for use in other applications." 
        />
      </div>
      <div className="mt-6 border-t border-slate-200 dark:border-slate-700 pt-6">
          <h3 className="text-lg font-semibold text-slate-800 dark:text-white">3 Things You Might Not Know</h3>
          <ul className="mt-2 space-y-2 list-disc list-inside text-slate-600 dark:text-slate-400">
            <li><span className="font-semibold text-slate-700 dark:text-slate-300">AI-Powered Data:</span> All rainfall data is generated by Google's Gemini model in real-time, providing a plausible and contextually aware dataset for the given coordinates.</li>
            <li><span className="font-semibold text-slate-700 dark:text-slate-300">Structured JSON Output:</span> The app requests a specific JSON schema from the AI, ensuring data consistency and preventing malformed responses from breaking the UI.</li>
            <li><span className="font-semibold text-slate-700 dark:text-slate-300">Dynamic CSV Generation:</span> The 'Download CSV' functionality is handled entirely in the browser, converting the displayed data into a downloadable file without any server interaction.</li>
          </ul>
      </div>
    </div>
  );
};
